<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<LanguageTargets>$(MSBuildToolsPath)\Microsoft.CSharp.targets</LanguageTargets>
		<TargetFrameworks>net472</TargetFrameworks>
		<RuntimeIdentifiers>win7-x64</RuntimeIdentifiers>
		<OutputType>WinExe</OutputType>
		<AssemblyTitle>PIComposer3dView</AssemblyTitle>
		<Product>PIComposer</Product>
		<Title>PIComposer3dView</Title>
		<Description>
			PIComposer 3dView is an adaptation of XbimXplorer for the purpose of displaying PIComposer ifc data.
		</Description>
		<ApplicationIcon />
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net472|AnyCPU'">
		<OutputPath>..\Output\Debug\</OutputPath>
		<PlatformTarget>x64</PlatformTarget>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net472|AnyCPU'">
		<OutputPath>..\Output\Release</OutputPath>
	</PropertyGroup>
	<PropertyGroup>
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
		<AssemblyName>PIComposer3dView</AssemblyName>
		<Authors>PIComposer</Authors>
		<Company>Procedure Information System, LLC</Company>
		<PackageProjectUrl>https://spatialcompute3d.com</PackageProjectUrl>
		<RepositoryUrl>https://github.com/chi-w-ng/XbimWebUI</RepositoryUrl>
		<PackageReleaseNotes>
     
    </PackageReleaseNotes>
		<!-- Disables WarningsAsErrors -->
	</PropertyGroup>
	<ItemGroup>
		<!-- App.xaml -->
		<ApplicationDefinition Include="App.xaml">
			<SubType>Designer</SubType>
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</ApplicationDefinition>
		<EmbeddedResource Update="Properties\Resources.resx" Generator="ResXFileCodeGenerator" LastGenOutput="Resources.Designer.cs" />
		<Compile Update="Properties\Resources.Designer.cs" DesignTime="True" AutoGen="True" DependentUpon="Resources.resx" />
		<Compile Update="Properties\Settings.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Settings.settings</DependentUpon>
		</Compile>
		<Compile Update="Settings.Designer.cs" AutoGen="True" DependentUpon="Settings.settings" />
		<None Update="Properties\Settings.settings">
			<Generator>SettingsSingleFileGenerator</Generator>
			<LastGenOutput>Settings.Designer.cs</LastGenOutput>
		</None>
		<None Update="Settings.settings" LastGenOutput="Settings.Designer.cs" Generator="SettingsSingleFileGenerator" />
		<Page Include="**\*.xaml" SubType="Designer" Generator="MSBuild:UpdateDesignTimeXaml" Exclude="App.xaml" />
		<Compile Update="**\*.xaml.cs" SubType="Designer" DependentUpon="%(Filename)" />
		<Resource Include="assets\*.*" />
		<Resource Include="Commands\console.bmp" />
		<Resource Include="**\*.png" />
	</ItemGroup>
	<ItemGroup>
		<None Remove="xBIM.ico" />
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include="xBIM.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</EmbeddedResource>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="AvalonDock" Version="2.0.2000" />
		<PackageReference Include="DotNetZip" Version="1.16.0" />
		<PackageReference Include="HelixToolkit.Wpf" Version="2.14.0" />
		<PackageReference Include="Nuget.Core" Version="2.14.0" />
		<PackageReference Include="PropertyTools.Wpf.DeploymentClone" Version="0.0.1" />
		<PackageReference Include="Serilog.Enrichers.Thread" Version="3.1.0" />
		<PackageReference Include="Serilog.Extensions.Logging" Version="2.0.4" />
		<PackageReference Include="Serilog.Sinks.File" Version="4.0.0" />
		<PackageReference Include="Xbim.Geometry" Version="5.1.437" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>
	<ItemGroup>
		<Reference Include="Microsoft.CSharp" />
		<Reference Include="PresentationCore" />
		<Reference Include="PresentationFramework" />
		<Reference Include="System.Data.DataSetExtensions" />
		<Reference Include="System.Windows.Forms" />
		<Reference Include="System.Xaml" />
		<Reference Include="WindowsBase" />
	</ItemGroup>
	<ItemGroup>
		<Folder Include="Properties\" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Xbim.Presentation\Xbim.Presentation.csproj" />
		<ProjectReference Include="..\..\XbimEssentials\Xbim.IO.Esent\Xbim.IO.Esent.csproj" />
	</ItemGroup>
</Project>